### ISSUE TITLE
Sonos Say Script Source/YAML

### ISSUE THREAD

**Issue by johnny-co** [scarpazza/home-assistant-konnected-tutorial#1]
can you point me to where you got the sonos say script or pass along your yaml please. otherwise making pretty good headway getting this working

**Comment by scarpazza** [comment]
Added. Let me know if it works for you.

**Comment by johnny-co** [comment]
Great thank you. That helped.

**Comment by scarpazza** [comment]
Fixed in commit 096bc81dc9299f35c8933e6210ba129d53dc619e
