### ISSUE TITLE
family group needs a colon

### ISSUE THREAD

**Issue by johnny-co** [scarpazza/home-assistant-konnected-tutorial#4]
Should have a : colon after the word family

family
  friendly_name: Family
  entity_id:
  - device_tracker.person1

**Comment by johnny-co** [comment]
Also dont see friendly_name in documentation. i think it should just be name: Family

**Comment by johnny-co** [comment]
actually it should be this, with entity_id pural to entities. last comment on this promise!
family:
  name: Family
  entities:
    - device_tracker.person1
    - device_tracker.person2
    - device_tracker.person3

**Comment by scarpazza** [comment]
Good catch!
